### ISSUE TITLE
errors in code

### ISSUE THREAD

**Issue by Monphito** [Arze1/CSGO-Overpay-Bot#19]
When someone sends this bot a offer it will pop up with an error here is the error:
                offerValue += offer.reduce((total, item) => total + prices[item.market_hash_name]);
                                    ^

TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at priceItemsInOffer (C:\csgobot1\bot.js:46:23)
    at TradeOfferManager.<anonymous> (C:\csgobot1\bot.js:116:13)
    at emitOne (events.js:96:13)
    at TradeOfferManager.emit (events.js:188:7)
    at received.forEach (C:\csgobot1\node_modules\steam-tradeoffer-manager\lib\polling.js:235:10)
    at Array.forEach (native)
    at getOffers (C:\csgobot1\node_modules\steam-tradeoffer-manager\lib\polling.js:219:12)
    at checkNeededDescriptions (C:\csgobot1\node_modules\steam-tradeoffer
manager\lib\classes\TradeOffer.js:117:4)
    at Async.map (C:\csgobot1\node_modules\steam-tradeoffer-manager\lib\assets.js:163:3)

**Comment by FreddyFish** [comment]
Weird, i have not been getting this before. 
Can you send your config? And remember to edit your personal details out! ;)

**Comment by Monphito** [comment]
I fixed this by nulling the array by making it var offer=[1,-1]  once reduced it fixed it

**Comment by FreddyFish** [comment]
Oh, great! 👍

**Comment by Monphito** [comment]
I need help fixing the bots accepting function

**Comment by Monphito** [comment]
If anyone else has this problem I will propose my fixes to arze

**Comment by w3bb0** [comment]
Just make a pr

**Comment by Monphito** [comment]
What is pr????

**Comment by w3bb0** [comment]
A pull request look on Google

**Comment by Monphito** [comment]
Ok
