### ISSUE TITLE
Error HELP PLZ

### ISSUE THREAD

**Issue by Monphito** [Arze1/CSGO-Overpay-Bot#22]
offerValue += offer.reduce((total, item) => total + prices[item.market_hash_name],0);
                                                                          ^

TypeError: Cannot read property 'R8 Revolver | Crimson Web (Well-Worn)' of null
    at offer.reduce (C:\csgobot1\bot.js:63:61)
    at Array.reduce (native)
    at priceItemsInOffer (C:\csgobot1\bot.js:63:23)
    at TradeOfferManager.<anonymous> (C:\csgobot1\bot.js:133:13)
    at emitOne (events.js:96:13)
    at TradeOfferManager.emit (events.js:188:7)
    at received.forEach (C:\csgobot1\node_modules\steam-tradeoffer-manager\lib\polling.js:235:10)
    at Array.forEach (native)
    at getOffers (C:\csgobot1\node_modules\steam-tradeoffer-manager\lib\polling.js:219:12)
    at checkNeededDescriptions (C:\csgobot1\node_modules\steam-tradeoffer-manager\lib\classes\TradeOffer.js:118:4)

**Comment by Monphito** [comment]
this is what pops up when someone sends a offer with skins that are under the minimium price
