### ISSUE TITLE
key must be a buffer

### ISSUE THREAD

**Issue by eaxxoi** [Arze1/CSGO-Overpay-Bot#33]
im probually not the smartest guy so please dont give me an answer i dont understand i just want to code my bot then im done with coding my problem is that when i try to launch my bot this comes up (sorry for bad english)

C:\Users\abc>node C:\Users\abc\Desktop\bot\bot.js
crypto.js:91
  this._handle.init(hmac, toBuf(key));
               ^

TypeError: Key must be a buffer
    at TypeError (native)
    at new Hmac (crypto.js:91:16)
    at Object.Hmac (crypto.js:89:12)
    at Object.exports.generateAuthCode.exports.getAuthCode (C:\Users\Liam\node_modules\steam-totp\index.js:41:20)
    at Object.<anonymous> (C:\Users\Liam\Desktop\botagain\bot.js:26:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by ghost** [comment]
Try wrapping it in a buffer, like so: 

`twoFactorCode:  SteamTotp.generateAuthCode(Buffer.from(config.sharedSecret))`

**Comment by eaxxoi** [comment]
how do i do that?

**Comment by ezraripps** [comment]
Look into bot.js

**Comment by eaxxoi** [comment]
C:\Users\Liam>node C:\Users\Liam\Desktop\andagain\bot.js
C:\Users\Liam\Desktop\andagain\bot.js:27
);
 ^
SyntaxError: Unexpected token ;

**Comment by eaxxoi** [comment]
fixed it but i cant use const in the script what do i do

**Comment by ezraripps** [comment]
Use var or let
