### ISSUE TITLE
help me please o my god :((

### ISSUE THREAD

**Issue by Silenttttttt** [Arze1/CSGO-Overpay-Bot#46]
when i try to run the bot i get thi error

module.js:590
    throw err;
    ^

SyntaxError: C:\Users\Muni\Desktop\CSGO-Overpay-Bot-master\config.json: Unexpected number in JSON at position 351
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Muni\Desktop\CSGO-Overpay-Bot-master\bot.js:10:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by FreddyFish** [comment]
Did you figure out what the problem was?
