### ISSUE TITLE
when the bot decline any offer i get this error

### ISSUE THREAD

**Issue by Silenttttttt** [Arze1/CSGO-Overpay-Bot#48]
Error: This trade offer is no longer valid.
    at SteamCommunity._checkTradeError (C:\Users\Muni\Desktop\CSGO-Overpay-Bot-master\node_modules\steamcommunity\components\http.js:144:13)
    at Request._callback (C:\Users\Muni\Desktop\CSGO-Overpay-Bot-master\node_modules\steamcommunity\components\http.js:52:80)
    at Request.self.callback (C:\Users\Muni\Desktop\CSGO-Overpay-Bot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Muni\Desktop\CSGO-Overpay-Bot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (C:\Users\Muni\Desktop\CSGO-Overpay-Bot-master\node_modules\request\request.js:1091:12)
    at Gunzip.g (events.js:291:16)

**Comment by Silenttttttt** [comment]
it works but why i get this error

**Comment by FreddyFish** [comment]
"Error: This trade offer is no longer valid."
I told you in your last issue, to stop the spamming comments. Edit the issue instead, no one even commented. 

When are you getting this error?

**Comment by Silenttttttt** [comment]
read the title

**Comment by Silenttttttt** [comment]
when the bot decline any offer i get this error

**Comment by ezraripps** [comment]
You know what, i really think this is a problem that we should fix BUT when people spam like this i don't think it is a problem we should fix.
