### ISSUE TITLE
Error: Access Denied

### ISSUE THREAD

**Issue by tismalheiro** [Arze1/CSGO-Overpay-Bot#53]
Error: Access Denied
    at SteamCommunity.<anonymous> (C:\Users\Tis\Desktop\CSGO-Overpay-Bot-master\node_modules\steamcommunity\components\webapi.js:15:20)
    at Request._callback (C:\Users\Tis\Desktop\CSGO-Overpay-Bot-master\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Users\Tis\Desktop\CSGO-Overpay-Bot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Tis\Desktop\CSGO-Overpay-Bot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (C:\Users\Tis\Desktop\CSGO-Overpay-Bot-master\node_modules\request\request.js:1091:12)
    at Gunzip.g (events.js:292:16)

I NEED HELP

**Comment by FreddyFish** [comment]
Your account is limited.

**Comment by Tos1c** [comment]
What do you mean by my account is limited because i got the same problem.

**Comment by Tos1c** [comment]
And how do you start the bot
There is no launch thingy??

**Comment by FreddyFish** [comment]
Account is limited. You have to deposit €/$5 into your stram account so you can use the API etc. etc.

**Comment by FreddyFish** [comment]
And if you dont know how to run this, you should probably not. Just.. dont even try.

**Comment by ezraripps** [comment]
Lol this is dumb @FreddyFish could you please make a PR to make readme say this, my pc broke ;(

**Comment by FreddyFish** [comment]
Sure, will do tomorrow when i find time.

**Comment by ezraripps** [comment]
Thanks alot!
