### ISSUE TITLE
Access Denied and DeprecationWarning

### ISSUE THREAD

**Issue by RChopin** [Arze1/CSGO-Overpay-Bot#62]
Steam Guard App Code: (node:----) [DEP----] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Steam Guard App Code: -----
Logged into Steam as [U:1:--------]
Error: Access Denied
    at SteamCommunity.<anonymous> (C:\Users\...\Desktop\Trade Bott\node_modules\steamcommunity\components\webapi.js:15:20)
    at Request._callback (C:\Users\...\Desktop\Trade Bott\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Users\...\Desktop\Trade Bott\node_modules\request\request.js:188:22)    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\P...\Desktop\Trade Bott\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Gunzip.<anonymous> (C:\Users\...\Desktop\Trade Bott\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
(node:----) [DEP----] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:----) [DEP----] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

That's what happens when I start the bot. Could you possibly help me?

**Comment by RChopin** [comment]
im idiot
